### ISSUE TITLE
Android(Linux)対応

### ISSUE THREAD

**Issue by hollimaple** [nisdon/pvr.epgtest.bin#1]
ソースコードがない以上、こちらでビルドすることが叶わないため、
誠に恐縮ですが、Android(Linux)対応いただけないでしょうか。

**Comment by hollimaple** [comment]
またはソースコードの開示いただけますと助かります。

**Comment by nisdon** [comment]
遅ればせながらAndroid対応致しました。
動作は自前のスマホ（arm64-v8a）で確認しております。
宜しければご使用下さい。
又、ソースの方は整理次第に公開させて頂きます。

**Comment by hollimaple** [comment]
Android対応ありがとうございます。arm64-v8aで動作確認できました。
後追いの情報で申し訳ございませんが、armeabi-v7aで対応できないでしょうか。

**Comment by nisdon** [comment]
既にリリースしているパッケージにバイナリーを含めました。
addon.xml内で定義している箇所を変更してご使用下さい。

**Comment by hollimaple** [comment]
迅速な対応ありがとうございます！
手持ちのAndroid端末においてKodi ver.19.4で動作確認できました。
これにてクローズとします。
