### ISSUE TITLE
エンコード済み録画の再生について

### ISSUE THREAD

**Issue by hatafugu** [nisdon/pvr.epgtest.bin#4]
こちらのバイナリを使おうと試みたのですが、録画の再生について上手く動作させられていません。
ソースファイルでの確認が出来ないので、できましたら動作の確認をお願いできないでしょうか？

- エンコード済みファイルしかない場合に再生できない。
- TSファイルがある場合は再生できるが、削除したファイルがある場合違うファイルが再生される。

確認した環境はWindows,FireTV,GoogleTVでKodi 18,19,20とも同様でした。

よろしくお願いします。

**Comment by nisdon** [comment]
ご指摘、有難うございます。

当該動作を確認しました。
結果、こちらの不具合と分り修正しました。
原因としては、epgstationより受けた録画ファイル識別子の扱い方が間違っていました。

この修正により、以下様に動作します。

- エンコード済みファイルがある場合は優先的に再生します。
- エンコード済みファイルが複数ある場合、最初に取得したファイル情報を用います。
- kodi起動中にエンコードした場合、pvr側の録画情報は自動で更新されません。

録画情報を更新するタイミングは、録画終了時です。
手動で行なうには、クライアント固有設定から「録画一覧を更新」を実行します。

以上の修正分として、先にkodi19用をアップしました。

**Comment by hatafugu** [comment]
確認、対応ありがとうございます。

まずは、提供いただいたkodi19用をwindows環境で確認してみましたが想定通りに動作しました。
可能でしたら、エンコード済みファイルを優先して再生するかは設定で選択できると嬉しいです。

引き続きkodi20用もよろしくお願いします。

**Comment by nisdon** [comment]
kodi20でも当該の不具合を修正してリリースしました。
併せて、先にご提案いただいた録画ファイルの優先設定を追加しています。

**Comment by hatafugu** [comment]
提供いただいたバージョンでWindowsのkodi19とFireTV,GoogleTVのkodi20で想定通りの動作が確認できました。
また、優先設定についても確認できました。

迅速な対応ありがとうございました。今後も便利に利用させていただきます。
